class_name PlayerProgress
extends Resource

## Player's map / stage progression: where the player stands and which stages are
## done. Phase 3 of the Area / Stage / StageType system (Coding Plan Rev 2),
## reshaped by Phase 7.6 (Global Stage Range model, Rev 3).
##
## This is the ONLY place player progression lives. Static authored data
## (StageData / StageDatabase) never stores completion, unlock, or current
## position — this object does, kept fully independent of those files.
##
## Distinguish from the battle-side PlayerProgression (scripts/player/
## player_progression.gd), which tracks the character's numeric growth
## (level / experience / gold / skills). This class tracks the map / stage
## path instead.
##
## Position is ONE number, and the area is derived
## ----------------------------------------------
## Stage numbers are global and never reset per area, so the position IS a stage
## number. The area the player is in is DERIVED from it
## (get_current_area_id → StageDatabase.database_for_stage). There is deliberately
## no stored `current_area_id`: a second stored copy of "where am I" is exactly
## what used to drift away from the battle's own stage number.
##
## Three fields answer three different questions, each with one writer
## ------------------------------------------------------------------
##   current_stage_number   "where am I now"      — can move backwards (defeat)
##   highest_stage_reached  "how far did I get"   — monotonic, the unlock basis
##   completed_stages       "which stages are DONE" — explicit clear records
##
## `highest_stage_reached` is required because past the last authored area no
## stage can be recorded as cleared, so a completed-set-only gate would deadlock
## at the end of the authored path. `completed_stages` is equally required: the
## stage the player currently stands on has not been cleared, so DONE cannot be
## derived from the position.
##
## Data format: completed_stages is a Dictionary keyed by the canonical stage id
## string produced by StageDatabase (e.g. "forest_006"), never by a Resource
## reference. Save / Load (Phase 8) serializes only these identifiers.

const StageDatabaseScript := preload("res://scripts/data/stage_database.gd")

## The GLOBAL stage number the player currently stands on. This is the only
## authoritative position in the game; the current area is derived from it.
@export_range(1, 999999, 1) var current_stage_number: int = 1
## The furthest GLOBAL stage number the player has ever REACHED. Monotonic: it
## never decreases, not even when a defeat pushes the player back a stage.
@export var highest_stage_reached: int = 1
## Canonical stage ids (as generated by StageDatabase) the player has cleared.
## Ids are used instead of Resource references so progress survives reload.
@export var completed_stages: Dictionary = {}


## Canonical StageDatabase id for a GLOBAL stage number, or "" when no authored
## area covers that number. StageDatabase is the single source of truth for the
## id format.
func _canonical_id(stage_number: int) -> String:
	var stage := StageDatabaseScript.lookup(stage_number)
	if stage == null:
		return ""
	return String(stage.id)


## The area the player currently stands in, DERIVED from the position, e.g.
## &"forest". Empty when the position is past every authored area (51+ in the
## default content), which is a legal state: those are plain endless stages.
func get_current_area_id() -> StringName:
	return StageDatabaseScript.area_for_stage(current_stage_number)


## Display name of the current area, or "" when none covers this position.
func get_current_area_name() -> String:
	var database := StageDatabaseScript.database_for_stage(current_stage_number)
	return database.display_name if database != null else ""


## True when the player may enter this GLOBAL stage: the first stage is always
## open, the next stage opens when the previous one is cleared, and any stage the
## player has already REACHED stays open (so a defeat rollback never re-locks the
## ground behind it).
##
## Both clauses are needed. The completion clause is what makes the authored path
## walkable one stage at a time on the map. The reach clause is what keeps the
## chain alive past the last authored area (51+ in the default content), where no
## stage can ever be recorded as cleared and a completion-only gate would
## deadlock: "I have been to stage N" is by itself the strongest unlock proof.
## Unlock is one global chain — crossing an area boundary (10 clears → 11 opens)
## needs no special rule.
func is_stage_unlocked(stage_number: int) -> bool:
	if stage_number < 1:
		return false
	if stage_number == 1 or stage_number <= highest_stage_reached:
		return true
	return is_stage_completed(stage_number - 1)


## True when the player has cleared this GLOBAL stage (its canonical id is
## recorded). A stage no authored area covers can never be completed.
func is_stage_completed(stage_number: int) -> bool:
	var stage_id := _canonical_id(stage_number)
	return not stage_id.is_empty() and completed_stages.has(stage_id)


## Records a cleared stage under its canonical id and returns true. Returns false
## (recording nothing) when no authored area covers that stage number. Only this
## progress object changes — the static database is never written.
func complete_stage(stage_number: int) -> bool:
	var stage_id := _canonical_id(stage_number)
	if stage_id.is_empty():
		return false
	completed_stages[stage_id] = true
	return true


## Records that the player has been at this GLOBAL stage number. Monotonic, so a
## defeat that moves the position backwards does not lower the unlock ceiling.
func mark_reached(stage_number: int) -> void:
	highest_stage_reached = maxi(highest_stage_reached, maxi(stage_number, 1))


## Current map position as a plain dictionary:
## { "stage_number", "area_id" (derived), "area_name" (derived) }.
func get_current_stage() -> Dictionary:
	return {
		"stage_number": current_stage_number,
		"area_id": get_current_area_id(),
		"area_name": get_current_area_name(),
	}
