class_name PlayerProgress
extends Resource

## Player's Area / Stage map progression: where the player stands and which
## stages are done. Phase 3 of the Area / Stage / StageType system (Coding
## Plan Rev 2).
##
## This is the ONLY place player progression lives. Static authored data
## (AreaData / StageData / StageDatabase) never stores completion, unlock, or
## current position — this object does, kept fully independent of those files.
##
## Distinguish from the battle-side PlayerProgression (scripts/player/
## player_progression.gd), which tracks the character's numeric growth
## (level / experience / gold / skills). This class tracks the map / stage
## path instead.
##
## Data format: completed_stages is a Dictionary keyed by the canonical stage id
## string produced by StageDatabase (e.g. "forest_006"), never by a Resource
## reference. Save / Load (Phase 8) serializes only these identifiers.

const StageDatabaseScript := preload("res://scripts/data/stage_database.gd")

## The Area the player currently stands in, e.g. &"forest". Empty until the
## player enters a stage (Phase 4+ routing). Kept as data only; advancement is
## a Phase 7 flow concern.
@export var current_area_id: StringName = &""
## Position within `current_area_id`, 1-based. Only meaningful while
## current_area_id is set.
@export_range(1, 999999, 1) var current_stage_number: int = 1
## Canonical stage ids (as generated by StageDatabase) the player has cleared.
## Ids are used instead of Resource references so progress survives reload.
@export var completed_stages: Dictionary = {}


## True when the authored database for `area_id` has a stage at `stage_number`.
## Keeps unlock / completion bounded by StageDatabase.stage_count without this
## class duplicating per-area counts.
func _area_has_stage(area_id: StringName, stage_number: int) -> bool:
	var database := StageDatabaseScript.load_area(area_id)
	if database == null:
		return false
	return stage_number >= 1 and stage_number <= database.stage_count


## Canonical StageDatabase id for (area, stage), or "" when no such stage
## exists. StageDatabase is the single source of truth for id format.
func _canonical_id(area_id: StringName, stage_number: int) -> String:
	var stage := StageDatabaseScript.lookup(area_id, stage_number)
	if stage == null:
		return ""
	return String(stage.id)


## True when the player may enter this stage: stage 1 of an authored area is
## always open; any later stage opens once the previous stage on the same path
## is completed. A stage that does not exist (un-authored area, out of range,
## number < 1) is never unlocked.
func is_stage_unlocked(area_id: StringName, stage_number: int) -> bool:
	if not _area_has_stage(area_id, stage_number):
		return false
	if stage_number == 1:
		return true
	return is_stage_completed(area_id, stage_number - 1)


## True when the player has cleared this stage (its canonical id is recorded).
func is_stage_completed(area_id: StringName, stage_number: int) -> bool:
	var stage_id := _canonical_id(area_id, stage_number)
	return not stage_id.is_empty() and completed_stages.has(stage_id)


## Records a cleared stage under its canonical id and returns true. Returns
## false (recording nothing) when the stage does not exist in an authored
## area. Only this progress object changes — the static database is never
## written.
func complete_stage(area_id: StringName, stage_number: int) -> bool:
	var stage_id := _canonical_id(area_id, stage_number)
	if stage_id.is_empty():
		return false
	completed_stages[stage_id] = true
	return true


## Current map position as a plain dictionary: { "area_id", "stage_number" }.
func get_current_stage() -> Dictionary:
	return {
		"area_id": current_area_id,
		"stage_number": current_stage_number,
	}
