extends SceneTree

## Generates the v4 analytic COMPARISON TABLE from the authoritative balance parameters.
##
## Run headless:
##   godot --headless --path . -s res://tools/balance_reference_table.gd
##
## The table is produced by the production code path — [BalanceProfile] +
## [BalanceFormulas] + [BalanceReferenceCase] — and never by hand, so a parameter edit moves
## the table with it. It prints to stdout and rewrites
## [code]docs/balance-reference-table.md[/code] in place; compare the numbers with the
## document model of [code]docs/balance-scale-rebase.md[/code] §7 and with the acceptance
## bands of [code]docs/balance-rework-implementation.md[/code] §8 M1/M2.

const PROFILE_PATH: String = "res://resources/balance/balance_profile_default.tres"
const OUTPUT_PATH: String = "res://docs/balance-reference-table.md"
## The stage sample of the §7 document model.
const TABLE_STAGES: Array[int] = [1, 3, 10, 20, 50, 100, 500, 1000]
const BOSS_STAGES: Array[int] = [10, 20, 50, 100, 500, 1000]

var _profile: BalanceProfile


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	_profile = load(PROFILE_PATH) as BalanceProfile
	if _profile == null:
		push_error("Could not load %s" % PROFILE_PATH)
		quit(1)
		return
	var report: String = _build_report()
	print(report)
	var file: FileAccess = FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Could not write %s (%d)" % [OUTPUT_PATH, FileAccess.get_open_error()])
		quit(1)
		return
	file.store_string(report)
	file.close()
	print("Wrote %s" % OUTPUT_PATH)
	quit(0)


func _build_report() -> String:
	var lines: Array[String] = []
	lines.append("# Balance v4 reference table (generated)")
	lines.append("")
	lines.append("> Generated by `godot --headless --path . -s res://tools/balance_reference_table.gd`.")
	lines.append("> Do not edit by hand — rerun the tool.")
	lines.append(">")
	lines.append("> Parameters: `%s` ([code]BalanceProfile[/code])." % PROFILE_PATH)
	lines.append("> Formulas: `res://scripts/balance/balance_formulas.gd`.")
	lines.append("> Fixture: `res://tests/fixtures/balance_reference_case.gd`.")
	lines.append(">")
	lines.append("> Case: L = il = S, seven Common (rarity 0) slots of item level S and no affixes,")
	lines.append("> normal reference enemy, offset 0, variance 1. `M_X = G(S)^0.6` under those")
	lines.append("> conditions, so every player stat is exactly `b_X × G(S)`. This isolates the")
	lines.append("> scale — it is not the mean of random drops.")
	lines.append("")
	lines.append("## Normal reference encounter")
	lines.append("")
	lines.append("| S | G(S) | item_scale | c | player HP | player ATK | player DEF | enemy HP | enemy ATK | enemy DEF | work | survival | actions | HP left |")
	lines.append("|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
	for stage: int in TABLE_STAGES:
		# Stage 1..training_stage_limit ships the fixed training base; the reference row
		# stays on the normal reference enemy so it remains comparable with §7.
		lines.append(_row_line(
			BalanceReferenceCase.build(_profile, stage),
			BalanceFormulas.is_training_stage(_profile, stage)
		))
	lines.append("")
	lines.append("`c` is the frozen encounter size; `actions` is the discrete M3 simulation")
	lines.append("(no criticals, no Sub Heroes, no healing, no distance) and `HP left` is the")
	lines.append("player's HP after clearing it. The row marked † keeps the normal reference enemy")
	lines.append("for the training stage so it stays comparable with the §7 document model; the")
	lines.append("shipped stage 1–%d base is in the training section below." % _profile.training_stage_limit)
	lines.append("")
	lines.append("## Mini Boss reference (c = %d basis, §4.3)" % _profile.boss_base_enemy_count)
	lines.append("")
	lines.append("| S | G(S) | boss HP | boss ATK | boss DEF | work | survival | actions | HP left |")
	lines.append("|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
	for stage: int in BOSS_STAGES:
		lines.append(_boss_line(BalanceReferenceCase.build(_profile, stage, true)))
	lines.append("")
	lines.append("## Training stages (fixed base, offset 0, variance 1)")
	lines.append("")
	lines.append("| S | c | player HP | player ATK | player DEF | enemy HP | enemy ATK | enemy DEF | work | survival | actions | HP left |")
	lines.append("|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
	for stage in range(1, _profile.training_stage_limit + 1):
		lines.append(_training_line(BalanceReferenceCase.build_training(_profile, stage)))
	lines.append("")
	lines.append("The M2 bands below start at stage 3: the training base is a fixed tutorial")
	lines.append("enemy and is deliberately easier than the compressed normal pool.")
	lines.append("")
	lines.append(_band_section())
	lines.append(_bound_section())
	lines.append("## Parameters behind the table")
	lines.append("")
	lines.append("| Parameter | Value |")
	lines.append("|---|---:|")
	lines.append("| G exponent / offset / divisor | %d / %s / %s |" % [
		_profile.growth_exponent, _profile.growth_offset, _profile.growth_divisor
	])
	lines.append("| σ (equipment share) | %.2f |" % _profile.equipment_share)
	lines.append("| level / item exponent | %.2f / %.2f |" % [
		_profile.get_level_exponent(), _profile.get_item_exponent()
	])
	lines.append("| b_HP / b_ATK / b_DEF | %s / %s / %s |" % [
		_profile.base_hp, _profile.base_attack, _profile.base_defense
	])
	lines.append("| count(S) | clamp(%d + floor((S-1)/%d), 1, %d) |" % [
		_profile.base_enemy_count, _profile.enemy_count_interval, _profile.max_enemy_count
	])
	lines.append("| difficulty(S) | %.2f → %.2f @ S%d → %.2f @ S%d |" % [
		_profile.difficulty_start, _profile.difficulty_mid, _profile.difficulty_mid_stage,
		_profile.difficulty_cap, _profile.difficulty_cap_stage
	])
	lines.append("| group exponents HP / ATK | %s / %s |" % [
		_profile.enemy_hp_count_exponent, _profile.enemy_attack_count_exponent
	])
	lines.append("| offset step / variance | %s / %s..%s |" % [
		_profile.enemy_offset_step, _profile.enemy_variance_min, _profile.enemy_variance_max
	])
	lines.append("| reference enemy HP/ATK/DEF/EXP | %s / %s / %s / %s |" % [
		_profile.reference_enemy_hp, _profile.reference_enemy_attack,
		_profile.reference_enemy_defense, _profile.reference_enemy_exp
	])
	lines.append("| training enemy HP/ATK/DEF/EXP | %s / %s / %s / %s |" % [
		_profile.training_enemy_hp, _profile.training_enemy_attack,
		_profile.training_enemy_defense, _profile.training_enemy_exp
	])
	lines.append("| Mini Boss multipliers HP/ATK/DEF | %s / %s / %s |" % [
		_profile.boss_hp_multiplier, _profile.boss_attack_multiplier,
		_profile.boss_defense_multiplier
	])
	lines.append("| crit baseline chance / damage | %.2f / %.2f |" % [
		_profile.base_critical_chance, _profile.base_critical_damage
	])
	lines.append("")
	return "\n".join(lines)


func _row_line(row: Dictionary, is_training_row: bool) -> String:
	var mark: String = " †" if is_training_row else ""
	return "| %d%s | %.3f | %.3f | %d | %d | %d | %d | %d | %d | %d | %.3f | %.3f | %d | %.1f%% |" % [
		int(row["stage"]), mark,
		float(row["g"]), float(row["item_scale"]), int(row["count"]),
		int(row["player_hp_int"]), int(row["player_attack_int"]), int(row["player_defense_int"]),
		int(row["enemy_hp_int"]), int(row["enemy_attack_int"]), int(row["enemy_defense_int"]),
		float(row["work"]), float(row["survival"]), int(row["actions"]),
		100.0 * float(row["hp_remaining"]),
	]


func _training_line(row: Dictionary) -> String:
	return "| %d | %d | %d | %d | %d | %d | %d | %d | %.3f | %.3f | %d | %.1f%% |" % [
		int(row["stage"]), int(row["count"]),
		int(row["player_hp_int"]), int(row["player_attack_int"]), int(row["player_defense_int"]),
		int(row["enemy_hp_int"]), int(row["enemy_attack_int"]), int(row["enemy_defense_int"]),
		float(row["work"]), float(row["survival"]), int(row["actions"]),
		100.0 * float(row["hp_remaining"]),
	]


func _boss_line(row: Dictionary) -> String:
	return "| %d | %.3f | %d | %d | %d | %.3f | %.3f | %d | %.1f%% |" % [
		int(row["stage"]), float(row["g"]),
		int(row["enemy_hp_int"]), int(row["enemy_attack_int"]), int(row["enemy_defense_int"]),
		float(row["work"]), float(row["survival"]), int(row["actions"]),
		100.0 * float(row["hp_remaining"]),
	]


func _band_section() -> String:
	var work_low: float = INF
	var work_high: float = -INF
	var work_low_stage: int = 0
	var work_high_stage: int = 0
	var survival_low: float = INF
	var survival_high: float = -INF
	var survival_low_stage: int = 0
	var survival_high_stage: int = 0
	var work_ok: bool = true
	var survival_ok: bool = true
	var actions_ok: bool = true
	var defeat_ok: bool = true
	for stage in range(3, _profile.max_stage + 1):
		var row: Dictionary = BalanceReferenceCase.build(_profile, stage)
		var work: float = float(row["work"])
		var survival: float = float(row["survival"])
		if work < work_low:
			work_low = work
			work_low_stage = stage
		if work > work_high:
			work_high = work
			work_high_stage = stage
		if survival < survival_low:
			survival_low = survival
			survival_low_stage = stage
		if survival > survival_high:
			survival_high = survival
			survival_high_stage = stage
		work_ok = work_ok and BalanceReferenceCase.is_work_in_band(_profile, stage, work)
		survival_ok = survival_ok and BalanceReferenceCase.is_survival_in_band(survival)
		if stage >= _profile.difficulty_mid_stage:
			actions_ok = actions_ok and int(row["actions"]) == BalanceReferenceCase.ACTIONS_LATE
			defeat_ok = defeat_ok and not bool(row["player_defeated"])
	var boss_actions_ok: bool = true
	var boss_defeat_ok: bool = true
	for stage in range(_profile.boss_interval, _profile.max_stage + 1, _profile.boss_interval):
		var row: Dictionary = BalanceReferenceCase.build(_profile, stage, true)
		var actions: int = int(row["actions"])
		boss_actions_ok = boss_actions_ok and actions >= BalanceReferenceCase.BOSS_ACTIONS_MIN and actions <= BalanceReferenceCase.BOSS_ACTIONS_MAX
		boss_defeat_ok = boss_defeat_ok and not bool(row["player_defeated"])
	var lines: Array[String] = []
	lines.append("## Acceptance bands (§8 M2)")
	lines.append("")
	lines.append("| Check | Range over the release stages | Verdict |")
	lines.append("|---|---|---|")
	lines.append("| encounter work, S3..%d | %.3f (S%d) .. %.3f (S%d) | %s |" % [
		_profile.max_stage,
		work_low, work_low_stage, work_high, work_high_stage,
		"PASS" if work_ok else "FAIL",
	])
	lines.append("| static survival, S3..%d | %.3f (S%d) .. %.3f (S%d) | %s |" % [
		_profile.max_stage,
		survival_low, survival_low_stage, survival_high, survival_high_stage,
		"PASS" if survival_ok else "FAIL",
	])
	lines.append("| cleared in exactly %d actions, S%d..%d | — | %s |" % [
		BalanceReferenceCase.ACTIONS_LATE, _profile.difficulty_mid_stage, _profile.max_stage,
		"PASS" if actions_ok else "FAIL",
	])
	lines.append("| reference player survives, S%d..%d | — | %s |" % [
		_profile.difficulty_mid_stage, _profile.max_stage,
		"PASS" if defeat_ok else "FAIL",
	])
	lines.append("| Mini Boss %d..%d actions with a surviving player | — | %s |" % [
		BalanceReferenceCase.BOSS_ACTIONS_MIN, BalanceReferenceCase.BOSS_ACTIONS_MAX,
		"PASS" if boss_actions_ok and boss_defeat_ok else "FAIL",
	])
	lines.append("")
	lines.append("The work band is 2..%.1f before S%d and 2..%.1f from S%d on; static survival is" % [
		BalanceReferenceCase.WORK_MAX_EARLY, _profile.difficulty_mid_stage,
		BalanceReferenceCase.WORK_MAX_LATE, _profile.difficulty_mid_stage,
	])
	lines.append("4..9 at every stage. `tools` output and the smoke test read the same band")
	lines.append("constants, so this verdict cannot drift from the assertion.")
	lines.append("")
	return "\n".join(lines)


func _bound_section() -> String:
	var max_scale: float = pow(BalanceFormulas.g(_profile, float(_profile.max_stage)), _profile.get_level_exponent())
	max_scale *= pow(BalanceFormulas.g(_profile, float(_profile.max_item_level)), _profile.get_item_exponent())
	var affix_budget: float = 1.4 + 7.0 * 0.1 * 2.75 * 1.2
	var lines: Array[String] = []
	lines.append("## Value bound at the release edge (§2)")
	lines.append("")
	lines.append("Maximum configuration: every slot Mythic at the highest roll, level %d, item level %d." % [
		_profile.max_character_level, _profile.max_item_level
	])
	lines.append("")
	lines.append("| Quantity | Value | Below MAX_COMBAT_VALUE (%s)? |" % _profile.max_combat_value)
	lines.append("|---|---:|---|")
	for stat_id in BalanceProfile.STAT_IDS:
		var value: float = _profile.get_base_stat(stat_id) * affix_budget * max_scale
		lines.append("| maximum %s | %s | %s |" % [
			stat_id, String.num(value, 4), "yes" if value < _profile.max_combat_value else "NO",
		])
	var maximum_attack: float = _profile.base_attack * affix_budget * max_scale
	var maximum_damage: float = maximum_attack * 1.9 * 1.5 * 2.5
	lines.append("| maximum damage chain (×1.9 skill ×1.5 type ×2.5 crit) | %s | %s |" % [
		String.num(maximum_damage, 4), "yes" if maximum_damage < _profile.max_combat_value else "NO",
	])
	lines.append("")
	return "\n".join(lines)
