extends SceneTree

## Runs the M5 progression simulation of the v4 balance contract (§8) against the production
## formulas and writes the release report.
##
## Run headless (the default run is the release gate: 100 seeds × S1..1000):
##   godot --headless --path . -s res://tools/balance_progression_sim.gd
##   godot --headless --path . -s res://tools/balance_progression_sim.gd -- --seeds 10 --max-stage 200
##
## It prints the report and rewrites [code]docs/balance-progression-simulation.md[/code], then
## exits non-zero when a §8 M5 release target is not met, so the same command can serve as the
## version gate.

const PROFILE_PATH: String = "res://resources/balance/balance_profile_default.tres"
const OUTPUT_PATH: String = "res://docs/balance-progression-simulation.md"

## The release run of §8 M5.
const DEFAULT_SEEDS: int = 100
const DEFAULT_MAX_STAGE: int = 1000


func _init() -> void:
	call_deferred("_run")


func _run() -> void:
	var profile := load(PROFILE_PATH) as BalanceProfile
	if profile == null:
		push_error("Could not load %s" % PROFILE_PATH)
		quit(1)
		return

	var arguments: Dictionary = _parse_arguments()
	if bool(arguments["sensitivity"]):
		_run_sensitivity(profile, arguments)
		return
	print("Running the M5 progression simulation (%d seeds × S1..%d)..." % [
		int(arguments["seeds"]), int(arguments["max_stage"])
	])
	var started: int = Time.get_ticks_msec()
	var report: Dictionary = BalanceProgressionSimulator.run(profile, {
		"seeds": arguments["seeds"],
		"max_stage": arguments["max_stage"],
		"special_encounters": arguments["special_encounters"],
		"verbose": arguments["verbose"],
		"trace_seed": arguments["trace_seed"],
	})
	var elapsed: float = float(Time.get_ticks_msec() - started) / 1000.0
	print(BalanceProgressionSimulator.format_report(report))
	print("  runtime %.1f s" % elapsed)

	if bool(arguments["write"]):
		_write_document(report, elapsed)

	var targets: Dictionary = BalanceProgressionSimulator.evaluate_targets(report)
	var failed: Array[String] = []
	for key in targets:
		if not bool(targets[key]):
			failed.append(str(key))
	if failed.is_empty():
		print("M5: every release target met.")
		quit(0)
		return
	push_error("M5: unmet release targets %s" % str(failed))
	quit(1)


## Decision aid, not a gate: how the M5 success statistics react to a stage-clear HP recovery — the
## one design lever behind the "20-encounter window" target (the shipped runtime restores nothing, so
## a bare strategy starts 70 % of its advances below half HP). Prints a table; writes nothing.
func _run_sensitivity(profile: BalanceProfile, arguments: Dictionary) -> void:
	print("M5 sensitivity: HP restored on a stage clear (%d seeds × S1..%d)" % [
		int(arguments["seeds"]), int(arguments["max_stage"])
	])
	print("  heal   first-push   advance success   worst 20-window   advance HP at start")
	for ratio in [0.0, 0.25, 0.5, 0.75, 1.0]:
		var report: Dictionary = BalanceProgressionSimulator.run(profile, {
			"seeds": arguments["seeds"],
			"max_stage": arguments["max_stage"],
			"clear_heal_ratio": ratio,
		})
		var success: Dictionary = report["success"]
		var loadout: Dictionary = report["loadout"]
		print("  %4.0f %%  %8.2f %%  %13.2f %%  %13.2f %%  %13.0f %%" % [
			ratio * 100.0,
			100.0 * float(success["first_push_rate_after_20"]),
			100.0 * float(success["rate_after_20"]),
			100.0 * float(success["worst_window_rate"]),
			100.0 * float(loadout["entry_hp_ratio_median"]),
		])
	# The other design lever: the potion SUPPLY (a §13 drop parameter) with no other change.
	print("")
	print("M5 sensitivity: potion supply — share of successful drops that is a potion (shipped %.0f %%)" % (
		100.0 * LootGenerator.CONSUMABLE_DROP_CHANCE
	))
	print("  potions   dropped/stage   drunk/stage   first-push   advance success   worst 20-window   HP at start")
	for chance in [0.15, 0.30, 0.45, 0.60]:
		var report: Dictionary = BalanceProgressionSimulator.run(profile, {
			"seeds": arguments["seeds"],
			"max_stage": arguments["max_stage"],
			"consumable_drop_chance": chance,
		})
		var success: Dictionary = report["success"]
		var loadout: Dictionary = report["loadout"]
		var stages: float = maxf(float(report["stages"]), 1.0)
		print("  %5.0f %%  %12.2f  %13.2f  %10.2f %%  %13.2f %%  %13.2f %%  %11.0f %%" % [
			chance * 100.0,
			float(report["potions"]) / stages,
			float(report["potions_used"]) / stages,
			100.0 * float(success["first_push_rate_after_20"]),
			100.0 * float(success["rate_after_20"]),
			100.0 * float(success["worst_window_rate"]),
			100.0 * float(loadout["entry_hp_ratio_median"]),
		])
	quit(0)


func _write_document(report: Dictionary, elapsed: float) -> void:
	var lines: Array[String] = []
	lines.append("# Balance v4 progression simulation (generated)")
	lines.append("")
	lines.append("> Generated by `godot --headless --path . -s res://tools/balance_progression_sim.gd`.")
	lines.append("> Do not edit by hand — rerun the tool.")
	lines.append(">")
	lines.append("> Model: `res://scripts/balance/balance_progression_simulator.gd` (M5 of")
	lines.append("> [balance-rework-implementation.md](balance-rework-implementation.md) §8).")
	lines.append("> Parameters: `%s`." % PROFILE_PATH)
	lines.append(">")
	lines.append("> The simulation drives the production formulas — `BalanceFormulas`,")
	lines.append("> `EnemyScaling`, `LootGenerator`/`EquipmentGenerator` and `EquipmentStatBlock` —")
	lines.append("> over real drops, real level-ups and the fixed §8 strategy. It is not a second copy")
	lines.append("> of the balance model; only the stage loop, the strategy and the seeded random")
	lines.append("> streams belong to it.")
	lines.append("")
	lines.append("```text")
	lines.append(BalanceProgressionSimulator.format_report(report))
	lines.append("  runtime %.1f s" % elapsed)
	lines.append("```")
	lines.append("")
	lines.append("## Trajectory parameters")
	lines.append("")
	lines.append("| Parameter | Value |")
	lines.append("|---|---|")
	lines.append("| Seeds | %d (first %d) |" % [int(report["seeds"]), int(report["first_seed"])])
	lines.append("| Stages | 1..%d |" % int(report["max_stage"]))
	lines.append("| Special encounters | %s |" % ("included (separate report)" if bool(report["special_encounters"]) else "excluded — the §5 release trajectory is normal + Mini Boss"))
	lines.append("| Combat strategy | normal attack, shortest legal route to the lowest-HP reachable enemy; no skills, potions, Tome or Sub Heroes |")
	lines.append("| Gear strategy | empty slot first; otherwise equip only when effective `ATK × HP` rises and static survival ≥ %.0f |" % BalanceProgressionSimulator.SWAP_SURVIVAL_MIN)
	lines.append("| Recovery | defeat revives at full HP, then up to %d replays of the highest cleared normal stage |" % BalanceProgressionSimulator.REPLAYS_PER_ADVANCE)
	lines.append("| Encounter failure | not cleared within %d player actions |" % BalanceProgressionSimulator.MAX_ACTIONS_PER_ENCOUNTER)
	lines.append("")
	lines.append("## Measured")
	lines.append("")
	var actions: Dictionary = report["actions"]
	var success: Dictionary = report["success"]
	var slot_fill: Dictionary = report["slot_fill"]
	var level: Dictionary = report["level"]
	var gear: Dictionary = report["gear_age"]
	var replays: Dictionary = report["replays"]
	lines.append("| Metric | Value | §8 M5 target |")
	lines.append("|---|---|---|")
	lines.append("| Seven slots filled before the first S10 challenge | %.1f %% | ≥ %.0f %% |" % [
		100.0 * float(slot_fill["ratio_before_s10"]),
		100.0 * BalanceProgressionSimulator.TARGET_SLOT_FILL_RATIO
	])
	lines.append("| Normal-encounter success after S20 | %.2f %% (%d challenges) | ≥ %.0f %% |" % [
		100.0 * float(success["rate_after_20"]), int(success["normal_challenges"]),
		100.0 * BalanceProgressionSimulator.TARGET_SUCCESS_RATE_AFTER_S20
	])
	lines.append("| Worst %d-encounter window after S20 | %.2f %% (%d windows) | ≥ %.0f %% |" % [
		BalanceProgressionSimulator.SUCCESS_WINDOW_STAGES, 100.0 * float(success["worst_window_rate"]),
		int(success["windows"]), 100.0 * BalanceProgressionSimulator.SUCCESS_WINDOW_MIN_RATE
	])
	lines.append("| Normal win attack actions (median / P90 / max) | %.1f / %.1f / %.1f | median %.0f..%.0f, P90 ≤ %.0f |" % [
		float(actions["normal_median"]), float(actions["normal_p90"]), float(actions["normal_max"]),
		BalanceProgressionSimulator.TARGET_NORMAL_ACTIONS_MEDIAN_MIN,
		BalanceProgressionSimulator.TARGET_NORMAL_ACTIONS_MEDIAN_MAX,
		BalanceProgressionSimulator.TARGET_NORMAL_ACTIONS_P90_MAX
	])
	lines.append("| Mini Boss win attack actions (median / P90) | %.1f / %.1f | median %.0f..%.0f |" % [
		float(actions["boss_median"]), float(actions["boss_p90"]),
		BalanceProgressionSimulator.TARGET_BOSS_ACTIONS_MEDIAN_MIN,
		BalanceProgressionSimulator.TARGET_BOSS_ACTIONS_MEDIAN_MAX
	])
	lines.append("| Movement turns per win (median / P90) | %.1f / %.1f | reported, not gated |" % [
		float(actions["movement_median"]), float(actions["movement_p90"])
	])
	lines.append("| Battle-start \\|L − S\\| ≤ 3 | %.2f %%, max %d | ≥ %.0f %%, max ≤ %d |" % [
		100.0 * float(level["abs_le_3_ratio"]), int(level["max_abs"]),
		100.0 * BalanceProgressionSimulator.TARGET_LEVEL_ABS_LE_3_RATIO,
		BalanceProgressionSimulator.TARGET_LEVEL_MAX_ABS
	])
	lines.append("| Gear lag after S20 (median / P90 / worst) | %.1f / %.1f / %.0f | published, not gated |" % [
		float(gear["median_lag"]), float(gear["p90_lag"]), float(gear["max_lag"])
	])
	lines.append("| Replays per advance (mean / P95 / max) | %.2f / %.1f / %d | ≤ %d |" % [
		float(replays["mean"]), float(replays["p95"]), int(replays["max"]),
		BalanceProgressionSimulator.TARGET_REPLAYS_PER_ADVANCE
	])
	lines.append("| Defeated trajectories | %d of %d | none required |" % [
		int(report["blocked_trajectories"]), int(report["seeds"])
	])
	lines.append("")
	lines.append("Gear handling over the run: %d equipment drops, %d potions, %d swaps, %d refused swaps." % [
		int(report["drops"]), int(report["potions"]), int(report["swaps"]), int(report["refused_swaps"])
	])
	lines.append("")
	lines.append("## Reading the numbers")
	lines.append("")
	lines.append("- The strategy is a reproducible ACCEPTANCE PROXY, not the player's AUTO logic and")
	lines.append("  not a claim that every build performs the same.")
	lines.append("- `c` is frozen at stage build, each surviving enemy retaliates once per player action")
	lines.append("  (M3 semantics), and the hero's HP is carried between stages, so the replay loop after")
	lines.append("  a defeat is the real recovery mechanism rather than an extra bonus.")
	lines.append("- Attack actions and movement turns are reported separately, so a run cannot hide a")
	lines.append("  damage shortfall behind standing still.")
	lines.append("- Level tracking is measured at BATTLE START (§5), not after the stage's own kills.")
	lines.append("")
	var file := FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Could not write %s (%d)" % [OUTPUT_PATH, FileAccess.get_open_error()])
		return
	file.store_string("\n".join(lines))
	file.close()
	print("Wrote %s" % OUTPUT_PATH)


## `--seeds N --max-stage N --special --verbose --no-write` after the `--` separator.
func _parse_arguments() -> Dictionary:
	var parsed: Dictionary = {
		"seeds": DEFAULT_SEEDS,
		"max_stage": DEFAULT_MAX_STAGE,
		"special_encounters": false,
		"verbose": false,
		"write": true,
		"trace_seed": 0,
		"sensitivity": false,
	}
	var arguments: PackedStringArray = OS.get_cmdline_user_args()
	var index: int = 0
	while index < arguments.size():
		var argument: String = arguments[index]
		match argument:
			"--seeds":
				if index + 1 < arguments.size():
					parsed["seeds"] = maxi(int(arguments[index + 1]), 1)
					index += 1
			"--max-stage":
				if index + 1 < arguments.size():
					parsed["max_stage"] = maxi(int(arguments[index + 1]), 1)
					index += 1
			"--trace-seed":
				if index + 1 < arguments.size():
					parsed["trace_seed"] = int(arguments[index + 1])
					index += 1
			"--special":
				parsed["special_encounters"] = true
			"--verbose":
				parsed["verbose"] = true
			"--no-write":
				parsed["write"] = false
			"--sensitivity":
				parsed["sensitivity"] = true
				parsed["write"] = false
			_:
				pass
		index += 1
	return parsed
